version: "3.9"
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes: 
      - postgres:/var/lib/postgresql/data

  orion:
    image: prefecthq/prefect:2-python3.10
    restart: always
    volumes:
      - prefect:/root/.prefect 
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0"]
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
      - PREFECT_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    depends_on:
      - database

  prefect-agent:
    image: noura039/prefect-agent:latest
    restart: always
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    volumes:
      - /home/ubuntu/start-agent.sh:/opt/flows/start-agent.sh
      - /home/ubuntu/Predictive-Maintenance-MLOps/src:/opt/flows/predictive_maintenance_project/src
    working_dir: /opt/flows
    depends_on:
      - orion
    command: ./start-agent.sh

volumes:
  prefect:
  postgres:
