---
- name: Deploy Prefect on EC2
  hosts: mlops
  become: yes
  tasks:
    - name: Copy start-agent.sh
      copy:
        src: start-agent.sh
        dest: /home/ubuntu/start-agent.sh
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose-prefect.yml
        dest: /home/ubuntu/docker-compose-prefect.yml
        mode: '0644'

    - name: Launch Prefect stack
      shell: docker-compose -f /home/ubuntu/docker-compose-prefect.yml up -d
      args:
        chdir: /opt/prefect
