version: "3.9"
services:
  ### PostgreSQL Database
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes: 
      - postgres:/var/lib/postgresql/data

  ### Prefect Orion API
  orion:
    image: prefecthq/prefect:2-python3.10
    restart: always
    volumes:
      - prefect:/root/.prefect 
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0"]

    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
      - PREFECT_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    depends_on:
      - database
  prefect-agent:
    image: prefect_image
    restart: always
    environment:
      - PREFECT_API_URL=http://orion:4200/api
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      #- ./:/opt/flows
      - ./start-agent.sh:/opt/flows/start-agent.sh
      - /home/predictive_maintenance_project/mlruns:/opt/flows/predictive_maintenance_project/mlruns
      - /home/predictive_maintenance_project/src:/opt/flows/predictive_maintenance_project/src
    working_dir: /opt/flows
    depends_on:
      - orion
    command: ./start-agent.sh

volumes:
  prefect:
  postgres: