- name: Deploy Jenkins
  hosts: mlops
  become: true
  vars:
    jenkins_compose_path: /home/ubuntu/docker-compose-jenkins.yml

  tasks:
    - name: Include Docker socket & permissions fix
      import_tasks: ./dockerpermissions.yml

    - name: Copy Jenkins Docker Compose file
      copy:
        src:  docker-compose-jenkins.yml
        dest: "{{ jenkins_compose_path }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start Jenkins container
      become_user: ubuntu
      shell: docker compose -f {{ jenkins_compose_path }} up -d
