version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: >
      bash -c "pip install psycopg2-binary &&
      mlflow server \
      --backend-store-uri postgresql://mlflow:mlflowpass@mlflow_postgres/mlflow_db \
      --default-artifact-root s3://mlops-project-artifacts-noura/mlflow/ \
      --host 0.0.0.0 \
      --port 5000"

    ports:
      - "5050:5000"
    
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflowpass
      POSTGRES_DB: mlflow_db
    volumes:
      - mlflow_pgdata:/var/lib/postgresql/data

volumes:
  mlflow_pgdata:
